export const skills = {
  Languages: [
    "JavaScript",
    "TypeScript",
    "Ruby",
    "Python",
    "SQL",
    "HTML",
    "CSS",
  ],
  Frontend: ["React", "Next.js", "Redux", "Tailwind CSS"],
  Backend: ["Node.js", "Ruby on Rails", "PostgreSQL", "REST APIs", "GraphQL"],
  "Testing & Quality": [
    "Cypress",
    "Jest",
    "React Testing Library",
    "TestRail",
    "Unit Testing",
    "Integration Testing",
    "End-to-End Testing",
  ],
  "Tooling & Platform": [
    "Git",
    "GitHub",
    "CI/CD",
    "Docker",
    "AWS (S3)",
    "Auth0",
    "Sanity CMS",
    "Datadog",
  ],
  "Collaboration & Tools": [
    "Jira",
    "Confluence",
    "Figma",
    "pgAdmin",
    "Postico",
  ],
  Methodologies: [
    "Agile / Scrum",
    "Test-Driven Development (TDD)",
    "Behavior-Driven Development (BDD)",
    "Code Reviews",
    "Continuous Improvement",
  ],
} as const;
